LIBS		= [
				'adolc',
				'blas',
				'atlas',
				'utpm',
				# 'utps',
			]
LIBPATH		= [
				'/home/b45ch1/workspace/ADOL-C/trunk/ADOL-C/src/.libs',
				'/home/b45ch1/workspace/taylorpoly/taylorpoly/taylorpoly',
		  ]
INCLUDEPATH	= [
			'../algorithms_for_adolc',
			'../algorithms_for_tapenade/c_code',
			'/home/b45ch1/workspace/ADOL-C/trunk/ADOL-C/src',
			'/home/b45ch1/workspace/taylorpoly/taylorpoly/taylorpoly/src',
			# '/home/b45ch1/workspace/taylorpoly/taylorpoly/3rdparty/lapack_headers',
			]

env = Environment(
	CPPPATH = INCLUDEPATH,
	# CXXFLAGS="-ftemplate-depth-100  -O3  -g -pg -DMTL_DISABLE_ALIGNMENT",
	CXXFLAGS="-ftemplate-depth-100  -O3 ",
	CFLAGS = "-O3",
	LIBPATH= LIBPATH,
	LIBS= LIBS,
	F77= 'gfortran',
	F77FLAGS = '-O3',
	RPATH = LIBPATH, #include information where shared libraries can be found to avoid errors like: "ImportError: libboost_python-gcc42-mt-1_34_1.so.1.34.1: cannot open shared object file: No such file or directory"
	SHLIBPREFIX="", #gets rid of lib prefix
)
Default('.')
# env.Program(target='matrix_ad_vs_adolc_vs_tapenade.exe',
# 	source=['matrix_ad_vs_adolc_vs_tapenade.cpp',
# 	'../algorithms_for_tapenade/fortran_code/dense_qr_decomposition_by_givens_rotations.f',
# 	'../algorithms_for_tapenade/fortran_code/dense_inverse.f',
# 	'../algorithms_for_tapenade/fortran_code/qr_b.f',
# 	'../algorithms_for_tapenade/fortran_code/inv_b.f',
# 	# '../algorithms_for_tapenade/fortran_code/adBuffer.f',
# 	'../algorithms_for_tapenade/fortran_code/adStack.c',
# 	'../algorithms_for_tapenade/fortran_code/adBuffer.c',
# 	'../algorithms_for_tapenade/c_code/inv_b.c',
# 	'../algorithms_for_tapenade/c_code/qr_b.c',
# 	'../algorithms_for_tapenade/c_code/dense_inverse.c',
# 	'../algorithms_for_tapenade/c_code/GlobalDeclarations_b.c',
	
# 	])

env.SharedLibrary(target='libtest_cases',
	source=['test_cases.cpp',
	'../algorithms_for_tapenade/fortran_code/adStack.c',
	'../algorithms_for_tapenade/fortran_code/adBuffer.c',
	'../algorithms_for_tapenade/c_code/inv_b.c',
	'../algorithms_for_tapenade/c_code/qr_b.c',
	'../algorithms_for_tapenade/c_code/dense_inverse.c',
	'../algorithms_for_tapenade/c_code/GlobalDeclarations_b.c',
    '/home/b45ch1/workspace/taylorpoly/taylorpoly/taylorpoly/src/utps.c'
	])


