LIBS		= [
				'adolc',
				'atlas',
				'blas',
				'lapack',
				'lapack_atlas',
				'f77blas',
			]
LIBPATH		= [
				'/u/walter/workspace/python_extension_for_adolc/adolc-2.0.0/adolc/.libs',
				'/data/walter/opt_software/SOLVIND_SUITE_27_05_2008/SOLVIND_SUITE/Packages/ATLAS/lib',
		  ]
INCLUDEPATH	= [
			'../algorithms_for_adolc',
			'/data/walter/opt_software/mtl4',
			'/u/walter/workspace/python_extension_for_adolc/adolc-2.0.0',
			'/data/walter/opt_software/SOLVIND_SUITE_27_05_2008/SOLVIND_SUITE/Packages/ATLAS/include',
			]

env = Environment(
	CPPPATH = INCLUDEPATH,
	CXXFLAGS="-ftemplate-depth-100  -O3  -g -pg -DMTL_DISABLE_ALIGNMENT",
	LIBPATH= LIBPATH,
	LIBS= LIBS,
	F77= 'g77-3.3',
	F77FLAGS = '-O2',
	RPATH = LIBPATH, #include information where shared libraries can be found to avoid errors like: "ImportError: libboost_python-gcc42-mt-1_34_1.so.1.34.1: cannot open shared object file: No such file or directory"
	SHLIBPREFIX="", #gets rid of lib prefix
)
Default('.')
env.Program(target='matrix_ad_vs_adolc_vs_tapenade.exe',
	source=['matrix_ad_vs_adolc_vs_tapenade.cpp',
	'../algorithms_for_tapenade/fortran_code/dense_qr_decomposition_by_givens_rotations.f',
	'../algorithms_for_tapenade/fortran_code/dense_inverse.f',
	'../algorithms_for_tapenade/fortran_code/qr_b.f',
	'../algorithms_for_tapenade/fortran_code/inv_b.f',
	'../algorithms_for_tapenade/fortran_code/adBuffer.f',
	'../algorithms_for_tapenade/fortran_code/adStack.c',
	#'../algorithms_for_tapenade/c_code/inv_b.c',
	#'../algorithms_for_tapenade/c_code/qr_b.c',
	#'../algorithms_for_tapenade/c_code/dense_inverse.c',
	])

