/*        Generated by TAPENADE     (INRIA, Tropics team)
    Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
*/
#include "GlobalDeclarations_b.c"

/*
  Differentiation of givens in reverse (adjoint) mode:
   gradient     of useful results: *s *c
   with respect to varying inputs: *s *a *b *c
   RW status of diff variables: *s:in-zero *a:out *b:out *c:in-zero
*/
void givens_b(double *a, double *ab, double *b, double *bb, double *c, double 
        *cb, double *s, double *sb) {
    /*
        Algorithm that computes c and s from a and b s.t.
        
          [ c   s  ] [a]     [r]
          [ -s   c ] [b]  =  [0]
        
        is satisfied.
        */
    double r;
    double rb;
    double result1;
    double result2;
    int givens;
    double temp0;
    double temp0b;
    double tempb;
    double temp;
    if (*b == 0.) {
        *ab = 0.0;
        *bb = 0.0;
    } else {
        result1 = fabs(*b);
        result2 = fabs(*a);
        if (result1 > result2) {
            r = -*a/(*b);
            *s = 1./sqrt(1+r*r);
            *sb = *sb + r*(*cb);
            temp = sqrt(r*r + 1);
            if (r*r + 1 == 0.0)
                rb = (*s)*(*cb);
            else
                rb = (*s)*(*cb) - 2*r*(*sb)/(pow(temp,3)*2.0);
            tempb = -(rb/(*b));
            *ab = tempb;
            *bb = -((*a)*tempb/(*b));
        } else {
            r = -*b/(*a);
            *c = 1./sqrt(1+r*r);
            *cb = *cb + r*(*sb);
            temp0 = sqrt(r*r + 1);
            if (r*r + 1 == 0.0)
                rb = (*c)*(*sb);
            else
                rb = (*c)*(*sb) - 2*r*(*cb)/(pow(temp0,3)*2.0);
            temp0b = -(rb/(*a));
            *bb = temp0b;
            *ab = -((*b)*temp0b/(*a));
        }
    }
    *sb = 0.0;
    *cb = 0.0;
}
