//        Generated by TAPENADE     (INRIA, Tropics team)
//  Tapenade 3.0 (r2511) - 07/23/2008 15:47
//  
//
//  Differentiation of inv in reverse (adjoint) mode:
//   gradient, with respect to input variables: *qt *a
//   of linear combination of output variables: *qt
//
void inv_b(double *a, double *ab, double *qt, double *qtb, double *r, int na) {
    int n, m, k;
    double rnn, rnm;
    double rnnb, rnmb;
    int result1;
    int res;
    int resb;
    int res0;
    double tmp;
    double tmpb;
    int res1;
    double tmp0;
    double tmp0b;
    int res2;
    int res2b;
    int res3;
    int res4;
    int res5;
    int res5b;
    double tmp1;
    double tmp1b;
    int branch;
    qr(a, qt, r, na);
    PUSHinteger4(0);
  label130:
    for(n = na - 1; n >= 0; --n)
    {
        res = myindex(n, n, na);
        PUSHreal8(rnn);
        rnn = *(r+res);
        PUSHinteger4(0);
      label100:
        for(m = 0; m != na; ++m)
        {
            result1 = myindex(n, m, na);
            tmp = *(r+result1)/rnn;
            PUSHpointer(*(r+res0));
            *(r+res0) = tmp;
            result1 = myindex(n, m, na);
            tmp0 = *(qt+result1)/rnn;
            PUSHpointer(*(qt+res1));
            *(qt+res1) = tmp0;
            PUSHinteger4(1);
            goto label100;
        }
        PUSHinteger4(0);
      label120:
        for(m = n + 1; m < na; ++m)
        {
            res2 = myindex(n, m, na);
            PUSHreal8(rnm);
            rnm = *(r+res2);
            *(r+res3) = 0;
            PUSHinteger4(0);
          label110:
            for(k = 0; k != na; ++k)
            {
                result1 = myindex(m, k, na);
                res5 = myindex(n, k, na);
                tmp1 = *(qt+res5) - (*(qt+result1))*rnm;
                PUSHpointer(*(qt+res4));
                *(qt+res4) = tmp1;
                PUSHinteger4(1);
                goto label110;
            }
            PUSHinteger4(1);
            goto label120;
        }
        PUSHinteger4(1);
        goto label130;
    }
    *rb = 0.0;
  label140:
    POPinteger4(branch);
    if (!(branch<1))
    {
      label150:
        POPinteger4(branch);
        if (!(branch<1))
        {
            rnmb = 0.0;
          label160:
            POPinteger4(branch);
            if (!(branch<1))
            {
                POPpointer(*(qt+res4));
                tmp1b = *;
                * = 0.0;
                * = * + tmp1b;
                * = * - rnm*tmp1b;
                rnmb = rnmb - (*(qt+result1))*tmp1b;
                goto label160;
            }
            POPreal8(rnm);
            * = rnmb;
            goto label150;
        }
        rnnb = 0.0;
      label170:
        POPinteger4(branch);
        if (!(branch<1))
        {
            POPpointer(*(qt+res1));
            tmp0b = *;
            * = 0.0;
            * = * + tmp0b/rnn;
            tmpb = *;
            rnnb = rnnb - (*(r+result1))*tmpb/(rnn*rnn) - (*(qt+result1))*tmp0b/(rnn*rnn);
            POPpointer(*(r+res0));
            * = 0.0;
            * = * + tmpb/rnn;
            goto label170;
        }
        POPreal8(rnn);
        * = * + rnnb;
        goto label140;
    }
    qr_b(a, ab, qt, qtb, r, rb, na);
}


