//        Generated by TAPENADE     (INRIA, Tropics team)
//  Tapenade 3.0 (r2511) - 07/23/2008 15:47
//  
//
//  Differentiation of qr in reverse (adjoint) mode:
//   gradient, with respect to input variables: *qt *a
//   of linear combination of output variables: *r *qt
//
void qr_b(double *a, double *ab, double *qt, double *qtb, double *r, double *rb, int na) {
    double arg1;
    int result1;
    int res;
    int res0;
    int res1;
    int res1b;
    int res2;
    int res2b;
    int res3;
    int res3b;
    int res4;
    int res4b;
    int res5;
    double tmp0;
    double tmp0b;
    int res6;
    double tmp1;
    double tmp1b;
    int res7;
    int res7b;
    int res8;
    double tmp2;
    double tmp2b;
    int res9;
    double tmp3;
    double tmp3b;
    int branch;
    PUSHinteger4(0);
    double at, bt, rt, ct, st, rnk, qtnk;
    double atb, btb, ctb, stb, rnkb, qtnkb;
    int n, m, k, tmp;
  label100:
    /* prepare Q and r */
    for(n = 0; n != na; ++n)
    {
        PUSHinteger4(0);
        for(m = 0; m != na; ++m)
        {
            if (n == m)
            {
                PUSHinteger4(1);
                tmp = 1;
            }
            else
            {
                PUSHinteger4(1);
                tmp = 0;
            }
            *(qt+res) = tmp;
        }
        PUSHinteger4(1);
        goto label100;
    }
    PUSHinteger4(0);
  label120:
    for(n = 0; n != na; ++n)
    {
        PUSHinteger4(0);
      label110:
        for(m = 0; m != na; ++m)
        {
            res1 = myindex(n, m, na);
            *(r+res0) = *(a+res1);
            PUSHinteger4(1);
            goto label110;
        }
        PUSHinteger4(1);
        goto label120;
    }
    PUSHinteger4(0);
  label150:
    /* MAIN ALGORITHM */
    for(n = 0; n != na; ++n)
    {
        PUSHinteger4(0);
      label140:
        for(m = n + 1; m != na; ++m)
        {
            /* defining coefficients of the Givens rotation */
            res2 = myindex(n, n, na);
            at = *(r+res2);
            res3 = myindex(m, n, na);
            bt = *(r+res3);
            arg1 = at*at + bt*bt;
            PUSHreal8(rt);
            rt = sqrt(arg1);
            PUSHreal8(ct);
            ct = at/rt;
            PUSHreal8(st);
            st = bt/rt;
            PUSHinteger4(0);
          label130:
            for(k = 0; k != na; ++k)
            {
                /* update r */
                res4 = myindex(n, k, na);
                PUSHreal8(rnk);
                rnk = *(r+res4);
                result1 = myindex(m, k, na);
                tmp0 = ct*rnk + st*(*(r+result1));
                PUSHpointer(*(r+res5));
                *(r+res5) = tmp0;
                result1 = myindex(m, k, na);
                tmp1 = -st*rnk + ct*(*(r+result1));
                PUSHpointer(*(r+res6));
                *(r+res6) = tmp1;
                /* update Q */
                res7 = myindex(n, k, na);
                PUSHreal8(qtnk);
                qtnk = *(qt+res7);
                result1 = myindex(m, k, na);
                tmp2 = ct*qtnk + st*(*(qt+result1));
                PUSHpointer(*(qt+res8));
                *(qt+res8) = tmp2;
                result1 = myindex(m, k, na);
                tmp3 = -st*qtnk + ct*(*(qt+result1));
                PUSHpointer(*(qt+res9));
                *(qt+res9) = tmp3;
                PUSHinteger4(1);
                goto label130;
            }
            PUSHinteger4(1);
            goto label140;
        }
        PUSHinteger4(1);
        goto label150;
    }
  label160:
    POPinteger4(branch);
    if (!(branch<1))
    {
      label170:
        POPinteger4(branch);
        if (branch < 1)
            goto label160;
        else
        {
            stb = 0.0;
            ctb = 0.0;
          label180:
            POPinteger4(branch);
            if (!(branch<1))
            {
                POPpointer(*(qt+res9));
                tmp3b = *;
                * = 0.0;
                * = * + ct*tmp3b;
                tmp2b = *;
                tmp1b = *;
                * = 0.0;
                * = * + ct*tmp1b;
                tmp0b = *;
                ctb = ctb + qtnk*tmp2b + rnk*tmp0b + (*(r+result1))*tmp1b + (*(qt+result1))*tmp3b;
                stb = stb + (*(qt+result1))*tmp2b + (*(r+result1))*tmp0b - rnk*tmp1b - qtnk*tmp3b;
                qtnkb = ct*tmp2b - st*tmp3b;
                POPpointer(*(qt+res8));
                * = 0.0;
                * = * + st*tmp2b;
                POPreal8(qtnk);
                * = * + qtnkb;
                POPpointer(*(r+res6));
                rnkb = ct*tmp0b - st*tmp1b;
                POPpointer(*(r+res5));
                * = 0.0;
                * = * + st*tmp0b;
                POPreal8(rnk);
                * = * + rnkb;
                goto label180;
            }
            POPreal8(st);
            btb = stb/rt;
            POPreal8(ct);
            atb = ctb/rt;
            POPreal8(rt);
            * = * + btb;
            * = * + atb;
            goto label170;
        }
    }
    *ab = 0.0;
  label190:
    POPinteger4(branch);
    if (!(branch<1))
    {
      label200:
        POPinteger4(branch);
        if (branch < 1)
            goto label190;
        else
        {
            * = * + *;
            *rb = 0.0;
            goto label200;
        }
    }
  label210:
    POPinteger4(branch);
    if (!(branch<1))
    {
      label220:
        POPinteger4(branch);
        if (branch < 1)
            goto label210;
        else
        {
            *qtb = 0.0;
            goto label220;
        }
    }
}


